Project rainbow {
  database_type: 'PostgreSQL'
  Note: 'Relational Database for Rainbow Data Platform'
}

Table users {
  id uuid [primary key]
  email varchar(100) [unique, not null]
  password varchar(255) [not null]
  first_name varchar(50)
  last_name varchar(50)
  last_login timestamp [default: null]
  is_active bool [default: true]
  phone_number varchar(20)
  role varchar(20) [default: 'USER', note: 'USER, ADMIN']
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table authors {
  id uuid [primary key]
  secondary_id varchar(100) [unique, default: null]
  name varchar(100) [not null]
  slug varchar(100) [not null]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table sellers {
  id uuid [primary key]
  secondary_id varchar(100) [unique, default: null]
  user_id uuid [ref: > users.id, unique, not null]
  name varchar(100) [not null, note: 'CHECK (length(name) > 0)']
  link varchar(255) [unique, not null]
  logo varchar(255) [unique, null]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table categories {
  id uuid [primary key]
  secondary_id varchar(100) [unique, default: null]
  name varchar(255) [not null, note: 'CHECK (length(name) > 0)']
  slug varchar(255) [not null, note: 'CHECK (length(slug) > 0)']
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table books {
  id uuid [pk]
  secondary_id varchar(100) [unique, default: null]
  category_id uuid [ref: > categories.id, not null]
  seller_id uuid [ref: > sellers.id, not null]
  name varchar(255) [not null, note: 'CHECK (length(name) > 0)']
  description text
  price decimal(10, 2) [not null, note: 'CHECK (price >= 0)']
  original_price decimal(10, 2) [not null, note: 'CHECK (original_price >= 0 AND original_price >= price)']
  rating_average decimal(2, 1) [not null, default: 0.0, note: 'CHECK (rating_average BETWEEN 0 AND 5)']
  review_count int [default: 0, note: 'CHECK (review_count >= 0)']
  page_count integer [note: 'CHECK (page_count >= 0)']
  sold_count integer [default: 0, note: 'CHECK (sold_count >= 0)']
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table book_authors {
  id uuid [pk]
  book_id uuid [ref: > books.id, not null]
  author_id uuid [ref: > authors.id, not null]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table payments {
  id uuid [pk]
  method varchar(20) [not null]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table orders {
  id uuid [pk]
  user_id uuid [ref: > users.id, not null]
  payment_id uuid [ref: > payments.id, not null]
  promotion_id uuid [ref: > promotions.id, null]
  shipping_address text [not null]
  total_amount decimal(10, 2) [not null, note: 'CHECK (total_amount >= 0)']
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table order_items {
  id uuid [pk]
  order_id uuid [ref: > orders.id, not null]
  book_id uuid [ref: > books.id, not null]
  quantity int [not null, note: 'CHECK (quantity > 0)']
  unit_price decimal(10, 2) [not null, note: 'CHECK (unit_price >= 0)']
  discount decimal(10, 2) [default: 0.00, note: 'CHECK (discount >= 0)']
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table inventories {
  id uuid [pk]
  book_id uuid [ref: > books.id, unique, not null]
  stock int [default: 0, note: 'CHECK (stock >= 0)']
  last_restocked_at timestamp
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table book_reviews {
  id uuid [pk]
  book_id uuid [ref: > books.id, not null]
  user_id uuid [ref: > users.id, not null]
  rating int [default: 5, note: 'rating between 1 and 5']
  likes_count int [default: 0]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
  indexes {
    (user_id, book_id) [unique]
  }
}

enum promotion_discount_type {
  PERCENTAGE
  FIXED
}

Table promotions {
  id uuid [pk]
  name varchar(100) [not null]
  discount_type promotion_discount_type [not null]
  discount_value decimal(10,2) [not null, note: 'CHECK (discount_value >= 0)']
  start_date timestamp [not null]
  end_date timestamp [not null, note: 'CHECK (end_date >= start_date)']
  max_uses int [not null, note: 'CHECK (max_uses >= 0)']
  used_count int [default: 0, note: 'CHECK (used_count >= 0)']
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
}

Table promotion_books {
  id uuid [pk]
  book_id uuid [ref: > books.id, not null]
  promotion_id uuid [ref: > promotions.id, not null]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
  indexes {
    (book_id, promotion_id) [unique]
  }
}

Table user_wishlist {
  id uuid [pk]
  user_id uuid [ref: > users.id, not null]
  book_id uuid [ref: > books.id, not null]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
  indexes {
    (user_id, book_id) [unique]
  }
}

Table user_promotions {
  id uuid [pk]
  user_id uuid [ref: > users.id, not null]
  promotion_id uuid [ref: > promotions.id, not null]
  used_at timestamp [default: `current_timestamp`]
  created_at timestamp [default: `current_timestamp`]
  updated_at timestamp [default: `current_timestamp`]
  deleted_at timestamp [default: null]
  indexes {
    (user_id, promotion_id) [unique]
  }
}
