apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cube-secret
  namespace: cube
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: google-secret-manager
    kind: ClusterSecretStore
  target:
    name: cube-secret
    creationPolicy: Owner
  data:
    - secretKey: CUBEJS_SQL_PASSWORD
      remoteRef:
        key: cubejs-sql-password
    - secretKey: CUBEJS_API_SECRET
      remoteRef:
        key: cubejs-api-secret
