default:
  target: development
  outputs:
    common: &common
      type: bigquery
      method: oauth
      threads: 4
      timeout_seconds: 3600
      location: us-central1
      priority: interactive
      retries: 1
    development:
      <<: *common
      project: rainbow-data-production
      dataset: dbt_temps
    production:
      <<: *common
      project: rainbow-data-production
      dataset: dbt_temps
