[project]
name = "airflow"
version = "0.1.0"
description = "Rainbow Apache Airflow project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow==2.10.4",
    "astronomer-cosmos>=1.8.2",
    "dbt-clickhouse>=1.8.8",
    "dbt-core==1.8.9",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.10.6",
]
