apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-secrets
  namespace: superset
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: google-secret-manager
    kind: ClusterSecretStore
  target:
    name: superset-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: github-oauth-client-id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: github-oauth-client-secret
    - secretKey: SUPERSET_SECRET_KEY
      remoteRef:
        key: superset-secret-key
