nameOverride: cubestore
fullnameOverride: cubestore

image:
  repository: cubejs/cubestore
  tag: v1.3.21
  pullPolicy: IfNotPresent

commonAnnotations:
  gke-gcsfuse/volumes: 'true'
  gke-gcsfuse/cpu-request: 100m
  gke-gcsfuse/memory-request: 128Mi
  gke-gcsfuse/cpu-limit: '1'
  gke-gcsfuse/memory-limit: 4Gi
  gke-gcsfuse/ephemeral-storage-request: 1Gi
  gke-gcsfuse/ephemeral-storage-limit: 2Gi

remoteDir:
  persistence:
    accessModes:
      - ReadWriteMany
    size: 100Gi
    storageClass: gcsfuse-static

exporter:
  enabled: false

router:
  serviceAccount:
    create: false
    name: cube
    annotations:
      iam.gke.io/gcp-service-account: cube-sa@rainbow-data-production.iam.gserviceaccount.com
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

workers:
  workersCount: 1
  serviceAccount:
    create: false
    name: cube
    annotations:
      iam.gke.io/gcp-service-account: cube-sa@rainbow-data-production.iam.gserviceaccount.com
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  initRouter:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 100m
        memory: 128Mi
    securityContext:
      runAsUser: 65532
      runAsGroup: 65532
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
