apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-storage
  namespace: kafka
  labels:
    app: kafka-cluster
    owner: tuan.tran
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-storage
  namespace: kafka
  labels:
    app: kafka-cluster
    owner: tuan.tran
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo
