apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: redpanda-gsa
  namespace: redpanda
  annotations:
    cnrm.cloud.google.com/project-id: rainbow-data-production
spec:
  resourceID: redpanda-sa
  displayName: RedPanda Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: redpanda-cloudsql-client
  namespace: redpanda
spec:
  member: serviceAccount:redpanda-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: rainbow-data-production
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: redpanda-cloudsql-instance-user
  namespace: redpanda
spec:
  member: serviceAccount:redpanda-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/cloudsql.instanceUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: rainbow-data-production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redpanda
  namespace: redpanda
  annotations:
    iam.gke.io/gcp-service-account: redpanda-sa@rainbow-data-production.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: redpanda-workload-identity
  namespace: redpanda
spec:
  member: serviceAccount:rainbow-data-production.svc.id.goog[redpanda/redpanda]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: redpanda-gsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpanda-role
rules:
  - apiGroups: ['']
    resources: [pods, pods/log, pods/status]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ['']
    resources: [configmaps, secrets]
    verbs: [get, list, watch]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redpanda-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redpanda-role
subjects:
  - kind: ServiceAccount
    name: redpanda
    namespace: redpanda
