apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cube-gsa
  namespace: cube
  annotations:
    cnrm.cloud.google.com/project-id: rainbow-data-production
spec:
  resourceID: cube-sa
  displayName: Cube Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cube-storage-admin
  namespace: cube
spec:
  member: serviceAccount:cube-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: rainbow-data-production-cubejs
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cube-dbt-storage-admin
  namespace: cube
spec:
  member: serviceAccount:cube-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: rainbow-data-production-dbt
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cube-bigquery-job-user
  namespace: cube
spec:
  member: serviceAccount:cube-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/bigquery.jobUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: rainbow-data-production
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cube-bigquery-data-owner
  namespace: cube
spec:
  member: serviceAccount:cube-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/bigquery.dataOwner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: rainbow-data-production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cube
  namespace: cube
  annotations:
    iam.gke.io/gcp-service-account: cube-sa@rainbow-data-production.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cube-workload-identity
  namespace: cube
spec:
  member: serviceAccount:rainbow-data-production.svc.id.goog[cube/cube]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: cube-gsa
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cube-sa-token-creator
  namespace: cube
spec:
  member: serviceAccount:cube-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/iam.serviceAccountTokenCreator
  resourceRef:
    kind: IAMServiceAccount
    name: cube-gsa
