apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-connect-secrets
  namespace: kafka
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: kafka-connect-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: rainbow-db-host
    - secretKey: DB_PORT
      remoteRef:
        key: rainbow-db-port
    - secretKey: CDC_DB_USER
      remoteRef:
        key: rainbow-cdc-db-user
    - secretKey: CDC_DB_PASSWORD
      remoteRef:
        key: rainbow-cdc-db-password
    - secretKey: CLICKHOUSE_HOST
      remoteRef:
        key: rainbow-clickhouse-host
    - secretKey: CLICKHOUSE_HTTP_PORT
      remoteRef:
        key: rainbow-clickhouse-http-port
    - secretKey: CLICKHOUSE_CDC_USER
      remoteRef:
        key: rainbow-clickhouse-cdc-user
    - secretKey: CLICKHOUSE_CDC_PASSWORD
      remoteRef:
        key: rainbow-clickhouse-cdc-password
