apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redpanda-storage
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
