# Redpanda Application Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redpanda
# TODO: Remove this once we want to re-enable Kafka UI
commonAnnotations:
  configmanagement.gke.io/managed: disabled
