// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/tuantran0910/rainbow/internal/controllers/v1/product"
	product2 "github.com/tuantran0910/rainbow/internal/repositories/product"
	product3 "github.com/tuantran0910/rainbow/internal/services/product"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeProductController(db *gorm.DB) (*product.ProductController, error) {
	iProductRepository := product2.NewProductRepository(db)
	iProductService := product3.NewProductService(db, iProductRepository)
	productController := product.NewProductController(iProductService)
	return productController, nil
}
