// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/tuantran0910/rainbow/internal/controllers"
	"github.com/tuantran0910/rainbow/internal/repositories"
	"github.com/tuantran0910/rainbow/internal/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeBookController(db *gorm.DB) (*controllers.BookController, error) {
	iBookRepository := repositories.NewBookRepository(db)
	iInventoryRepository := repositories.NewInventoryRepository(db)
	iSellerRepository := repositories.NewSellerRepository(db)
	iUserRepository := repositories.NewUserRepository(db)
	iBookService := services.NewBookService(db, iBookRepository, iInventoryRepository, iSellerRepository, iUserRepository)
	bookController := controllers.NewBookController(iBookService)
	return bookController, nil
}

func InitializeAuthController(db *gorm.DB) (*controllers.AuthController, error) {
	iUserRepository := repositories.NewUserRepository(db)
	iAuthService := services.NewAuthService(db, iUserRepository)
	authController := controllers.NewAuthController(iAuthService)
	return authController, nil
}

func InitializeUserController(db *gorm.DB) (*controllers.UserController, error) {
	iUserRepository := repositories.NewUserRepository(db)
	iUserService := services.NewUserService(db, iUserRepository)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}

func InitializeSellerController(db *gorm.DB) (*controllers.SellerController, error) {
	iSellerRepository := repositories.NewSellerRepository(db)
	iUserRepository := repositories.NewUserRepository(db)
	iSellerService := services.NewSellerService(db, iSellerRepository, iUserRepository)
	sellerController := controllers.NewSellerController(iSellerService)
	return sellerController, nil
}

func InitializeCategoryController(db *gorm.DB) (*controllers.CategoryController, error) {
	iCategoryRepository := repositories.NewCategoryRepository(db)
	iUserRepository := repositories.NewUserRepository(db)
	iCategoryService := services.NewCategoryService(db, iCategoryRepository, iUserRepository)
	categoryController := controllers.NewCategoryController(iCategoryService)
	return categoryController, nil
}

func InitializeAuthorController(db *gorm.DB) (*controllers.AuthorController, error) {
	iAuthorRepository := repositories.NewAuthorRepository(db)
	iUserRepository := repositories.NewUserRepository(db)
	iAuthorService := services.NewAuthorService(db, iAuthorRepository, iUserRepository)
	authorController := controllers.NewAuthorController(iAuthorService)
	return authorController, nil
}

func InitializePaymentController(db *gorm.DB) (*controllers.PaymentController, error) {
	iPaymentRepository := repositories.NewPaymentRepository(db)
	iPaymentService := services.NewPaymentService(iPaymentRepository)
	paymentController := controllers.NewPaymentController(iPaymentService)
	return paymentController, nil
}
