x-dagster-common: &dagster-common
  build:
    context: ${DAGSTER_PROJ_DIR:-../../src/dagster_core/local}
    dockerfile: Dockerfile
  env_file:
    - ./.env
  depends_on: &dagster-common-depends-on
    postgres:
      condition: service_healthy
  restart: always
  networks:
    - dagster-network

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: ${DB_HOST}
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgres/postgresql.conf:/etc/postgresql.conf
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    healthcheck:
      test: [CMD, pg_isready, -U, '${DB_USER}']
      interval: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - postgres-network
      - dagster-network

  api:
    build:
      context: ../../src/api
      dockerfile: Dockerfile
    container_name: api
    hostname: ${API_HOST}
    ports:
      - ${SERVER_PORT:-5000}:${SERVER_PORT}
    volumes:
      - ../../src/api/migrations:/migrations
    env_file:
      - ./.env
    healthcheck:
      test: [CMD, curl, --fail, 'http://localhost:${SERVER_PORT}/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
      - api-network

  dagster-webserver:
    <<: *dagster-common
    container_name: dagster-webserver
    entrypoint:
      - dagster-webserver
      - -h
      - 0.0.0.0
      - -p
      - '3000'
      - -w
      - workspace.yaml
    ports:
      - 3001:3000
    depends_on:
      <<: *dagster-common-depends-on
    networks:
      - dagster-network
      - postgres-network
      - minio-network

  dagster-daemon:
    <<: *dagster-common
    container_name: dagster-daemon
    entrypoint:
      - dagster-daemon
      - run
    depends_on:
      <<: *dagster-common-depends-on
    networks:
      - dagster-network
      - postgres-network
      - minio-network

  dagster-workspace:
    build:
      context: ${DAGSTER_WORKSPACE_PROJ_DIR:-../../src/dagster_workspace}
      dockerfile: Dockerfile
    container_name: dagster-workspace
    image: dagster-workspace
    environment:
      DAGSTER_CURRENT_IMAGE: dagster-workspace
      API_BASE_URL: http://${API_HOST}:${SERVER_PORT}
    entrypoint:
      - dagster
      - code-server
      - start
      - -h
      - 0.0.0.0
      - -p
      - 4000
      - -m
      - definitions
    volumes:
      - ${DAGSTER_WORKSPACE_PROJ_DIR:-../../src/dagster_workspace}:/opt/dagster/app
      - ${DAGSTER_DBT_PROJ_DIR:-../../src/dbt/local}:/opt/dagster/app/dbt
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - dagster-network
      - minio-network
      - api-network

  clickhouse:
    image: clickhouse/clickhouse-server:25.3-alpine
    container_name: clickhouse
    hostname: ${CLICKHOUSE_HOST}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - ${CLICKHOUSE_HTTP_PORT}:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./configs/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./configs/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./scripts/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:8123/ping]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - dagster-network
      - clickhouse-network

  redpanda:
    image: redpandadata/redpanda:v25.1.1
    container_name: redpanda
    hostname: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr=internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr=internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr=internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr=redpanda:33145
      - --advertise-rpc-addr=redpanda:33145
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    volumes:
      - redpanda:/var/lib/redpanda/data
    healthcheck:
      test: [CMD-SHELL, rpk cluster health | grep -E 'Healthy:.+true' || exit 1]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - redpanda-network

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.9.0
    container_name: connect
    hostname: connect
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.5.4
        confluent-hub install --no-prompt clickhouse/clickhouse-kafka-connect:v1.2.6
        /etc/confluent/docker/run
    environment:
      CONNECT_BOOTSTRAP_SERVERS: redpanda:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://redpanda:8081
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://redpanda:8081
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_LOG4J_LOGGERS: org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars,/usr/share/confluent-hub-components
      CONNECT_CONFIG_PROVIDERS: env
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: org.apache.kafka.common.config.provider.EnvVarConfigProvider
    env_file:
      - ./.env
    ports:
      - 8083:8083
    volumes:
      - ./connectors:/etc/kafka-connect/jars/
      - kafka-connect-plugins:/usr/share/confluent-hub-components
    depends_on:
      - redpanda
    restart: always
    healthcheck:
      test: [CMD, curl, --fail, http://connect:8083/]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - postgres-network
      - redpanda-network
      - clickhouse-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    hostname: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://redpanda:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: local-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
    ports:
      - 8082:8080
    depends_on:
      - redpanda
      - kafka-connect
    restart: always
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, http://localhost:8080/actuator/health]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - redpanda-network

  kafka-init-connectors:
    image: ellerbrock/alpine-bash-curl-ssl
    container_name: kafka-init-connectors
    depends_on:
      kafka-connect:
        condition: service_healthy
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    volumes:
      - ${KAFKA_PROJ_DIR:-../../src/kafka}/connectors:/connectors
    entrypoint: bash -c '/connectors/start.sh'
    networks:
      - redpanda-network

  metabase:
    image: metabase/metabase:v0.53.5.4
    container_name: metabase
    hostname: ${METABASE_HOST}
    ports:
      - ${METABASE_PORT:-3000}:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB_NAME}
      MB_DB_PORT: ${DB_PORT}
      MB_DB_USER: ${METABASE_DB_USER}
      MB_DB_PASS: ${METABASE_DB_PASSWORD}
      MB_DB_HOST: ${DB_HOST}
    env_file:
      - ./.env
    volumes:
      - /dev/urandom:/dev/random:ro
      - metabase-data:/metabase-data
    healthcheck:
      test: [CMD, curl, --fail, -I, http://localhost:3000/api/health]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - postgres
    restart: always
    networks:
      - metabase-network
      - postgres-network
      - cube-network

  cubestore_worker:
    image: cubejs/cubestore:v1.2.19
    container_name: cubestore_worker
    hostname: cubestore_worker
    environment:
      CUBESTORE_WORKERS: cubestore_worker:10000
      CUBESTORE_SERVER_NAME: cubestore_worker:10000
      CUBESTORE_WORKER_PORT: 10000
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - cubestore:/cube/data
    depends_on:
      - cubestore_router
    restart: always
    networks:
      - cube-network
      - clickhouse-network

  cubestore_router:
    image: cubejs/cubestore:v1.2.19
    container_name: cubestore_router
    hostname: cubestore_router
    environment:
      CUBESTORE_WORKERS: cubestore_worker:10000
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_PORT: 9999
      CUBESTORE_SERVER_NAME: cubestore_router:9999
    volumes:
      - cubestore:/cube/data
    restart: always
    networks:
      - cube-network
      - clickhouse-network

  cube_refresh_worker:
    image: cubejs/cube:v1.2.19
    container_name: cube_refresh_worker
    hostname: cube_refresh_worker
    environment:
      CUBEJS_DB_TYPE: clickhouse
      CUBEJS_DB_HOST: ${CLICKHOUSE_HOST}
      CUBEJS_DB_PORT: ${CLICKHOUSE_HTTP_PORT}
      CUBEJS_DB_USER: ${CLICKHOUSE_CUBEJS_USER}
      CUBEJS_DB_PASS: ${CLICKHOUSE_CUBEJS_PASSWORD}
      CUBEJS_DB_NAME: ${CLICKHOUSE_CUBEJS_DB_NAME}
      CUBEJS_PG_SQL_PORT: 15432
      CUBEJS_SQL_USER: ${CUBEJS_SQL_USER}
      CUBEJS_SQL_PASS: ${CUBEJS_SQL_PASSWORD}
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: ${CUBE_API_SECRET:-secret}
      CUBEJS_REFRESH_WORKER: true
    volumes:
      - ${CUBE_PROJ_DIR:-../../src/cube}:/cube/conf
    restart: always
    networks:
      - cube-network
      - clickhouse-network

  cube_api:
    image: cubejs/cube:v1.2.19
    container_name: cube_api
    hostname: cube_api
    ports:
      - ${CUBE_API_PORT:-4000}:4000
      - ${CUBE_SQL_API_PORT:-15432}:15432
    environment:
      CUBEJS_DEV_MODE: ${CUBEJS_DEV_MODE:-false}
      CUBEJS_DB_TYPE: clickhouse
      CUBEJS_DB_HOST: ${CLICKHOUSE_HOST}
      CUBEJS_DB_PORT: ${CLICKHOUSE_HTTP_PORT}
      CUBEJS_DB_USER: ${CLICKHOUSE_CUBEJS_USER}
      CUBEJS_DB_PASS: ${CLICKHOUSE_CUBEJS_PASSWORD}
      CUBEJS_DB_NAME: ${CLICKHOUSE_CUBEJS_DB_NAME}
      CUBEJS_PG_SQL_PORT: 15432
      CUBEJS_SQL_USER: ${CUBEJS_SQL_USER}
      CUBEJS_SQL_PASS: ${CUBEJS_SQL_PASSWORD}
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: ${CUBE_API_SECRET:-secret}
    volumes:
      - ${CUBE_PROJ_DIR:-../../src/cube}:/cube/conf
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker
    restart: always
    networks:
      - cube-network
      - clickhouse-network

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: minio
    hostname: ${MINIO_HOST}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    env_file:
      - ./.env
    ports:
      - 9002:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: [CMD, curl, -f, http://localhost:9000/minio/health/live]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - minio-network

  minio-client:
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z
    container_name: minio-client
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - ./scripts/minio/init.sh:/init.sh
    entrypoint: [/bin/bash, /init.sh]
    networks:
      - minio-network

volumes:
  postgres_data:
  clickhouse_data:
  metabase-data:
  cubestore:
  minio_data:
  redpanda:
  kafka-connect-plugins:

networks:
  dagster-network:
    driver: bridge
  postgres-network:
    driver: bridge
  api-network:
    driver: bridge
  clickhouse-network:
    driver: bridge
  redpanda-network:
    driver: bridge
  metabase-network:
    driver: bridge
  cube-network:
    driver: bridge
  minio-network:
    driver: bridge
