x-dagster-common: &dagster-common
  build:
    context: ${DAGSTER_PROJ_DIR:-../../src/dagster}
    dockerfile: Dockerfile
  env_file:
    - ./.env
  depends_on: &dagster-common-depends-on
    postgres:
      condition: service_healthy
  restart: always
  networks:
    - dagster-network

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: ${DB_HOST}
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgres/postgresql.conf:/etc/postgresql.conf
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    healthcheck:
      test: [CMD, pg_isready, -U, '${DB_USER}']
      interval: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - postgres-network
      - dagster-network

  api:
    build:
      context: ../../src/api
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    ports:
      - ${SERVER_PORT:-5000}:${SERVER_PORT}
    volumes:
      - ../../src/api/migrations:/migrations
    env_file:
      - ./.env
    healthcheck:
      test: [CMD, curl, --fail, 'http://localhost:${SERVER_PORT}/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
      - api-network

  dagster-webserver:
    <<: *dagster-common
    container_name: dagster-webserver
    entrypoint:
      - dagster-webserver
      - -h
      - 0.0.0.0
      - -p
      - '3000'
      - -w
      - workspace.yaml
    ports:
      - 3001:3000
    healthcheck:
      test: [CMD, curl, --fail, http://localhost:3000/health]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      <<: *dagster-common-depends-on
    networks:
      - dagster-network
      - postgres-network
      - minio-network

  dagster-daemon:
    <<: *dagster-common
    container_name: dagster-daemon
    entrypoint:
      - dagster-daemon
      - run
    healthcheck:
      test: [CMD, curl, --fail, http://localhost:8974/health]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      <<: *dagster-common-depends-on
    networks:
      - dagster-network
      - postgres-network
      - minio-network

  dagster-workspace:
    build:
      context: ${DAGSTER_WORKSPACE_PROJ_DIR:-../../src/dagster_workspace}
      dockerfile: Dockerfile
    container_name: dagster-workspace
    image: dagster-workspace
    environment:
      DAGSTER_CURRENT_IMAGE: dagster-workspace
    volumes:
      - ${DAGSTER_WORKSPACE_PROJ_DIR:-../../src/dagster_workspace}:/opt/dagster/app
    env_file:
      - ./.env
    networks:
      - dagster-network
      - minio-network

  clickhouse:
    image: clickhouse/clickhouse-server:24.12
    container_name: clickhouse
    hostname: ${CLICKHOUSE_HOST}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - ${CLICKHOUSE_PORT}:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./configs/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./configs/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./scripts/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:8123/ping]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - dagster-network
      - clickhouse-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    ports:
      - 2181:2181
    healthcheck:
      test: [CMD, sh, -c, echo ruok | nc localhost 2181]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - kafka-network

  kafka-broker:
    image: confluentinc/cp-kafka:7.9.0
    container_name: broker
    hostname: broker
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
    ports:
      - 9092:9092
      - 29092:29092
      - 9999:9999
    healthcheck:
      test: [CMD, sh, -c, nc -z localhost 9092]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - zookeeper
    restart: always
    networks:
      - kafka-network

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.9.0
    container_name: schema-registry
    hostname: schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka-broker
    restart: always
    healthcheck:
      test: [CMD, timeout, '1', curl, --silent, --fail, http://schema-registry:8081/subjects]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - kafka-network

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.9.0
    container_name: connect
    hostname: connect
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.5.4
        confluent-hub install --no-prompt clickhouse/clickhouse-kafka-connect:v1.2.6
        /etc/confluent/docker/run
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker:29092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_LOG4J_LOGGERS: org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars,/usr/share/confluent-hub-components
      CONNECT_CONFIG_PROVIDERS: env
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: org.apache.kafka.common.config.provider.EnvVarConfigProvider
    env_file:
      - ./.env
    ports:
      - 8083:8083
    volumes:
      - ./connectors:/etc/kafka-connect/jars/
    depends_on:
      - zookeeper
      - kafka-broker
      - kafka-schema-registry
    restart: always
    healthcheck:
      test: [CMD, curl, --fail, http://connect:8083/]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - postgres-network
      - kafka-network
      - clickhouse-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    hostname: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: local-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - 8082:8080
    depends_on:
      - zookeeper
      - kafka-broker
      - kafka-schema-registry
      - kafka-connect
    restart: always
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, http://localhost:8080/actuator/health]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - kafka-network

  kafka-init-connectors:
    image: ellerbrock/alpine-bash-curl-ssl
    container_name: kafka-init-connectors
    depends_on:
      kafka-connect:
        condition: service_healthy
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    volumes:
      - ${KAFKA_PROJ_DIR:-../../src/kafka}/connectors:/connectors
    entrypoint: bash -c '/connectors/start.sh'
    networks:
      - kafka-network

  metabase:
    image: metabase/metabase:v0.53.5.4
    container_name: metabase
    hostname: ${METABASE_HOST}
    ports:
      - ${METABASE_PORT:-3000}:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB_NAME}
      MB_DB_PORT: ${DB_PORT}
      MB_DB_USER: ${METABASE_DB_USER}
      MB_DB_PASS: ${METABASE_DB_PASSWORD}
      MB_DB_HOST: ${DB_HOST}
    env_file:
      - ./.env
    volumes:
      - /dev/urandom:/dev/random:ro
      - metabase-data:/metabase-data
    healthcheck:
      test: [CMD, curl, --fail, -I, http://localhost:3000/api/health]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - postgres
    restart: always
    networks:
      - metabase-network
      - postgres-network
      - cube-network

  cubestore_worker:
    image: cubejs/cubestore:v1.2.19
    container_name: cubestore_worker
    hostname: cubestore_worker
    environment:
      CUBESTORE_WORKERS: cubestore_worker:10000
      CUBESTORE_SERVER_NAME: cubestore_worker:10000
      CUBESTORE_WORKER_PORT: 10000
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - cubestore:/cube/data
    depends_on:
      - cubestore_router
    restart: always
    networks:
      - cube-network
      - clickhouse-network

  cubestore_router:
    image: cubejs/cubestore:v1.2.19
    container_name: cubestore_router
    hostname: cubestore_router
    environment:
      CUBESTORE_WORKERS: cubestore_worker:10000
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_PORT: 9999
      CUBESTORE_SERVER_NAME: cubestore_router:9999
    volumes:
      - cubestore:/cube/data
    restart: always
    networks:
      - cube-network
      - clickhouse-network

  cube_refresh_worker:
    image: cubejs/cube:v1.2.19
    container_name: cube_refresh_worker
    hostname: cube_refresh_worker
    environment:
      CUBEJS_DB_TYPE: clickhouse
      CUBEJS_DB_HOST: ${CLICKHOUSE_HOST}
      CUBEJS_DB_PORT: ${CLICKHOUSE_PORT}
      CUBEJS_DB_USER: ${CLICKHOUSE_CUBEJS_USER}
      CUBEJS_DB_PASS: ${CLICKHOUSE_CUBEJS_PASSWORD}
      CUBEJS_DB_NAME: ${CLICKHOUSE_CUBEJS_DB_NAME}
      CUBEJS_PG_SQL_PORT: 15432
      CUBEJS_SQL_USER: ${CUBEJS_SQL_USER}
      CUBEJS_SQL_PASS: ${CUBEJS_SQL_PASSWORD}
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: ${CUBE_API_SECRET:-secret}
      CUBEJS_REFRESH_WORKER: true
    volumes:
      - ${CUBE_PROJ_DIR:-../../src/cube}:/cube/conf
    restart: always
    networks:
      - cube-network
      - clickhouse-network

  cube_api:
    image: cubejs/cube:v1.2.19
    container_name: cube_api
    hostname: cube_api
    ports:
      - ${CUBE_API_PORT:-4000}:4000
      - ${CUBE_SQL_API_PORT:-15432}:15432
    environment:
      CUBEJS_DEV_MODE: ${CUBEJS_DEV_MODE:-false}
      CUBEJS_DB_TYPE: clickhouse
      CUBEJS_DB_HOST: ${CLICKHOUSE_HOST}
      CUBEJS_DB_PORT: ${CLICKHOUSE_PORT}
      CUBEJS_DB_USER: ${CLICKHOUSE_CUBEJS_USER}
      CUBEJS_DB_PASS: ${CLICKHOUSE_CUBEJS_PASSWORD}
      CUBEJS_DB_NAME: ${CLICKHOUSE_CUBEJS_DB_NAME}
      CUBEJS_PG_SQL_PORT: 15432
      CUBEJS_SQL_USER: ${CUBEJS_SQL_USER}
      CUBEJS_SQL_PASS: ${CUBEJS_SQL_PASSWORD}
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: ${CUBE_API_SECRET:-secret}
    volumes:
      - ${CUBE_PROJ_DIR:-../../src/cube}:/cube/conf
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker
    restart: always
    networks:
      - cube-network
      - clickhouse-network

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: minio
    hostname: ${MINIO_HOST}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    env_file:
      - ./.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: [CMD, curl, -f, http://localhost:9000/minio/health/live]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - minio-network

  minio-client:
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z
    container_name: minio-client
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - ./scripts/minio/init.sh:/init.sh
    entrypoint: [/bin/bash, /init.sh]
    networks:
      - minio-network

volumes:
  postgres_data:
  clickhouse_data:
  metabase-data:
  cubestore:
  minio_data:

networks:
  dagster-network:
    driver: bridge
  postgres-network:
    driver: bridge
  api-network:
    driver: bridge
  clickhouse-network:
    driver: bridge
  kafka-network:
    driver: bridge
  metabase-network:
    driver: bridge
  cube-network:
    driver: bridge
  minio-network:
    driver: bridge
