apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: external-secrets-gsa
  namespace: external-secrets
  annotations:
    cnrm.cloud.google.com/project-id: rainbow-data-production
spec:
  resourceID: external-secrets-sa
  displayName: External Secrets Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: external-secrets-secret-manager-secret-accessor
  namespace: external-secrets
spec:
  member: serviceAccount:external-secrets-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: rainbow-data-production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: external-secrets-sa@rainbow-data-production.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: external-secrets-workload-identity
  namespace: external-secrets
spec:
  member: serviceAccount:rainbow-data-production.svc.id.goog[external-secrets/external-secrets]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: external-secrets-gsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-controller
rules:
  - apiGroups: ['']
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ['']
    resources: [configmaps]
    verbs: [get, list, watch]
  - apiGroups: ['']
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [external-secrets.io]
    resources: [externalsecrets, secretstores, clustersecretstores, clusterexternalsecrets, pushsecrets, clusterpushsecrets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [external-secrets.io]
    resources: [externalsecrets/status, secretstores/status, clustersecretstores/status, clusterexternalsecrets/status, pushsecrets/status, clusterpushsecrets/status]
    verbs: [get, update, patch]
  - apiGroups: [external-secrets.io]
    resources: [externalsecrets/finalizers, secretstores/finalizers, clustersecretstores/finalizers, clusterexternalsecrets/finalizers, pushsecrets/finalizers,
      clusterpushsecrets/finalizers]
    verbs: [update]
  - apiGroups: [generators.external-secrets.io]
    resources: ['*']
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-controller
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
