apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: dagster-database
  namespace: dagster
  annotations:
    cnrm.cloud.google.com/project-id: rainbow-data-production
spec:
  name: dagster
  instanceRef:
    name: rainbow-data-production-db
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: dagster-user
  namespace: dagster
  annotations:
    cnrm.cloud.google.com/project-id: rainbow-data-production
spec:
  instanceRef:
    name: rainbow-data-production-db
  resourceID: dagster-sa@rainbow-data-production.iam
  type: CLOUD_IAM_SERVICE_ACCOUNT
