apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dagster-secrets
  namespace: dagster
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: google-secret-manager
    kind: ClusterSecretStore
  target:
    name: dagster-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_DB_PASSWORD
      remoteRef:
        key: api-password
