apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-workspace-pv
  labels:
    app: dagster
    owner: tuan.tran
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  gcePersistentDisk:
    pdName: rainbow-data-production-dagster-workspace-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dagster-workspace-pvc
  namespace: dagster
  labels:
    app: dagster
    owner: tuan.tran
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: dagster-workspace-pv
  storageClassName: ''
