apiVersion: v1
kind: Secret
metadata:
  name: dagster-postgresql-secret
  namespace: dagster
type: Opaque
data:
  postgresql-password: ''
  postgresql-username: ZGFnc3Rlci1zYUByYWluYm93LWRhdGEtcHJvZHVjdGlvbi5pYW0=
  postgresql-host: bG9jYWxob3N0
  postgresql-port: NTQzMg==
  postgresql-database: ZGFnc3Rlcg==
