apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: dagster-gsa
  namespace: dagster
  annotations:
    cnrm.cloud.google.com/project-id: rainbow-data-production
spec:
  resourceID: dagster-sa
  displayName: Dagster Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: dagster-cloudsql-client
  namespace: dagster
spec:
  member: serviceAccount:dagster-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: rainbow-data-production
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: dagster-cloudsql-instance-user
  namespace: dagster
spec:
  member: serviceAccount:dagster-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/cloudsql.instanceUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: rainbow-data-production
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: dagster-storage-admin
  namespace: dagster
spec:
  member: serviceAccount:dagster-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: rainbow-data-production-dagster
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: dagster
#   namespace: dagster
#   annotations:
#     iam.gke.io/gcp-service-account: dagster-sa@rainbow-data-production.iam.gserviceaccount.com
# ---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: dagster-workload-identity
  namespace: dagster
spec:
  member: serviceAccount:rainbow-data-production.svc.id.goog[dagster/dagster]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: dagster-gsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dagster-role
rules:
  - apiGroups: ['']
    resources: [pods, pods/log, pods/status]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ['']
    resources: [configmaps, secrets]
    verbs: [get, list, watch]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dagster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dagster-role
subjects:
  - kind: ServiceAccount
    name: dagster
    namespace: dagster
