[project]
name = "dagster-workspace"
version = "0.1.0"
description = "Rainbow Dagster Workspace"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster>=1.10.20",
    "dagster-dbt>=0.26.20",
    "dagster-postgres>=0.26.20",
    "dagster-dlt>=0.26.20",
    "psutil>=7.0.0",
    "faker>=37.1.0",
    "dbt-core>=1.9.8",
]

[dependency-groups]
local = [
    "dagster-obstore>=0.2.3",
    "dlt[clickhouse,postgres]>=1.11.0",
    "dbt-clickhouse>=1.9.2",
]

cloud = [
    "dlt[bigquery,postgres]>=1.11.0",
    "dbt-bigquery>=1.9.2",
]
