apiVersion: v1
kind: Namespace
metadata:
  name: dagster
---
apiVersion: v1
kind: Namespace
metadata:
  name: superset
---
apiVersion: v1
kind: Namespace
metadata:
  name: redpanda
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnrm-system
  labels:
    name: cnrm-system
