apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: google-secret-manager
spec:
  provider:
    gcpsm:
      projectID: rainbow-data-production
      auth:
        workloadIdentity:
          clusterName: rainbow-data-production
          clusterLocation: us-central1
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
