name: dlt_rainbow
enabled: true
group_name: dlt
job:
  name: dlt_rainbow_job
  description: Job to run dlt pipeline
schedule:
  name: dlt_rainbow_schedule
  description: Schedule to run dlt pipeline
  cron_schedule: 0 */4 * * *
  execution_timezone: UTC
resources:
  source:
    type: sql_database
    credentials:
      drivername: postgresql+psycopg2
      host: localhost
      port: 5432
      # NOTE: We are facing some issues with the permissions of the EL user.
      # So we are using the API user instead.
      username: rainbow
      password: env:API_DB_PASSWORD
      database: rainbow
    schema:
      name: public
      tables:
        - name: orders
          incremental_field: updated_at
        - name: order_items
          incremental_field: updated_at
        - name: books
          incremental_field: updated_at
        - name: authors
          incremental_field: updated_at
        - name: promotions
          incremental_field: updated_at
        - name: payments
          incremental_field: updated_at
        - name: categories
          incremental_field: updated_at
        - name: users
          incremental_field: updated_at
        - name: sellers
          incremental_field: updated_at
        - name: book_authors
          incremental_field: updated_at
  destination:
    type: bigquery
    dataset_name: rainbow
    credentials:
      project_id: rainbow-data-production
    configs:
      location: us-central1
      autodetect_schema: false
