default:
  target: development
  outputs:
    common: &common
      type: clickhouse
      port: 8123
      threads: 1
      secure: false
    development:
      <<: *common
      host: localhost
      user: dbt
      password: "{{ env_var('CLICKHOUSE_DBT_PASSWORD') }}"
      schema: raw
    production:
      <<: *common
      host: clickhouse
      user: dbt
      password: "{{ env_var('CLICKHOUSE_DBT_PASSWORD') }}"
      schema: raw
