apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: dagster-repo-sync
  namespace: dagster
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/tuantran0910/rainbow.git
    branch: main
    dir: deployments/cloud/k8s/applications/dagster
    auth: none
  override:
    enableShellInRendering: false
