apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/tuantran0910/rainbow.git
    branch: main
    dir: deployments/cloud/k8s/cluster
    auth: none
  override:
    enableShellInRendering: false
