[project]
name = "dagster-core"
version = "0.1.0"
description = "Rainbow Dagster project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster==1.10.9",
    "dagster-graphql>=1.10.9",
    "dagster-postgres>=0.26.9",
    "dagster-webserver>=1.10.9",
    "dagster-obstore>=0.2.3",
    "psutil>=7.0.0",
]
