[project]
name = "dagster-core"
version = "0.1.0"
description = "Rainbow Dagster project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster>=1.10.6",
    "dagster-aws>=0.26.6",
    "dagster-docker>=0.26.6",
    "dagster-graphql>=1.10.6",
    "dagster-postgres>=0.26.6",
    "dagster-webserver>=1.10.6",
]
