airflow:
  dag_id: dummy_dbt
  description: A DAG for running dbt jobs
  schedule_interval: 0 0 * * *
  start_date: '2021-01-01'
  timezone: UTC
  catchup: false
  max_active_runs: 1
  default_args:
    owner: rainbow
    retries: 3
    retry_delay_seconds: 300
    email_on_failure: false
    email_on_retry: false
    depends_on_past: false
  tags:
    - dbt
    - dummy
    - airflow
    - example

dbt:
  select:
    - path:models/example
    - tag:daily
    - tag:cleansed
  exclude:
    - tag:test
