apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: kafka-gsa
  namespace: kafka
  annotations:
    cnrm.cloud.google.com/project-id: rainbow-data-production
spec:
  resourceID: kafka-sa
  displayName: Kafka Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kafka-cloudsql-client
  namespace: kafka
spec:
  member: serviceAccount:kafka-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: rainbow-data-production
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kafka-gcs-storage-admin
  namespace: kafka
spec:
  member: serviceAccount:kafka-sa@rainbow-data-production.iam.gserviceaccount.com
  role: roles/storage.admin
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: rainbow-data-production-kafka
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: kafka
  annotations:
    iam.gke.io/gcp-service-account: kafka-sa@rainbow-data-production.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kafka-workload-identity
  namespace: kafka
spec:
  member: serviceAccount:rainbow-data-production.svc.id.goog[kafka/kafka]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kafka-gsa
