name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AI Code Review
        uses: lfsevergnini/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Choose the LLM provider and key
          AI_PROVIDER: google
          AI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AI_MODEL: gemini-1.5-flash
          AI_TEMPERATURE: 0.5

          # Additional configurations
          APPROVE_REVIEWS: false
          MAX_COMMENTS: 10
          PROJECT_CONTEXT: >
            This is a backend and data engineer project that simulates a data platform.
            We have backend API written in Golang as our application. Data is stored in a PostgreSQL database.
            Data then is processed and transformed using the Lambda architecture with batch layer in dbt and streaming layer in Kafka.
            We are currently using ClickHouse as our data warehouse, Apache Superset as our BI tool, and Apache Airflow as our scheduler.
            The project is containerized using Docker.
          CONTEXT_FILES: README.md
          EXCLUDE_PATTERNS: '**/*.lock,**/*.md'
